In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets

### load the dataset

In [2]:
df_flights = pd.read_csv('../datasets/flights.csv')

In [19]:
df_flights.head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier tailnum  \
0  2014      1    1       1.0       96.0     235.0       70.0      AS  N508AS   
1  2014      1    1       4.0       -6.0     738.0      -23.0      US  N195UW   
2  2014      1    1       8.0       13.0     548.0       -4.0      UA  N37422   
3  2014      1    1      28.0       -2.0     800.0      -23.0      US  N547UW   
4  2014      1    1      34.0       44.0     325.0       43.0      AS  N762AS   

   flight origin dest  air_time  distance  hour  minute  
0     145    PDX  ANC     194.0      1542   0.0     1.0  
1    1830    SEA  CLT     252.0      2279   0.0     4.0  
2    1609    PDX  IAH     201.0      1825   0.0     8.0  
3     466    PDX  CLT     251.0      2282   0.0    28.0  
4     121    SEA  ANC     201.0      1448   0.0    34.0

In [30]:
df_flights.shape

(162049, 16)

In [23]:
df_flights['carrier'].unique()

array(['AS', 'US', 'UA', 'DL', 'AA', 'F9', 'VX', 'OO', 'WN', 'B6', 'HA'],
      dtype=object)

In [24]:
df_flights['origin'].unique()

array(['PDX', 'SEA'], dtype=object)

### Logical operators

In [5]:
True and False

False

In [6]:
True or False

True

In [7]:
not False

True

### Bitwise operators

In [22]:
print(np.binary_repr(10))
print(np.binary_repr(15))
print(np.binary_repr(10 & 15))
print(np.binary_repr(10 | 15))

1010
1111
1010
1111


In [14]:
True & False

False

In [15]:
True | False

True

## Element-wise

### bitwise operation using numpy

In [16]:
np.array([True, True, False]) & np.array([True, False, False])

array([ True, False, False])

In [17]:
np.array([True, True, False]) | np.array([True, False, False])

array([ True,  True, False])

In [26]:
np.array([True, True, False]) & \
np.array([True, False, False]) & \
np.array([True, False, True]) & \
np.array([True, True, True]) 

array([ True, False, False])

### numpy.logical_and

In [23]:
np.logical_and([True, True, False], [True, False, False])

array([ True, False, False])

In [24]:
np.logical_or([True, True, False], [True, False, False])

array([ True,  True, False])

In [25]:
np.logical_and.reduce([[True, True, False], 
                       [True, False, False],
                       [True, False, True],
                       [True, True, True]])

array([ True, False, False])

## performing selection by multiple conditions

In [3]:
df_flights.loc[ np.logical_and(df_flights['carrier'] == "AA", df_flights['origin'] == "SEA") ].head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
13  2014      1    1     557.0       -3.0    1134.0      -16.0      AA   
17  2014      1    1     600.0        0.0    1151.0      -19.0      AA   
58  2014      1    1     704.0       -6.0    1245.0      -20.0      AA   
62  2014      1    1     708.0       -7.0    1510.0      -19.0      AA   
86  2014      1    1     810.0      -10.0    1419.0      -11.0      AA   

   tailnum  flight origin dest  air_time  distance  hour  minute  
13  N3JLAA    1094    SEA  DFW     184.0      1660   5.0    57.0  
17  N3JFAA    2240    SEA  ORD     206.0      1721   6.0     0.0  
58  N3KNAA    1308    SEA  DFW     188.0      1660   7.0     4.0  
62  N3DNAA     236    SEA  JFK     281.0      2422   7.0     8.0  
86  N3DSAA    1236    SEA  ORD     202.0      1721   8.0    10.0

In [4]:
df_flights.loc[ (df_flights['carrier'] == "AA") & (df_flights['origin'] == "SEA") ].head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
13  2014      1    1     557.0       -3.0    1134.0      -16.0      AA   
17  2014      1    1     600.0        0.0    1151.0      -19.0      AA   
58  2014      1    1     704.0       -6.0    1245.0      -20.0      AA   
62  2014      1    1     708.0       -7.0    1510.0      -19.0      AA   
86  2014      1    1     810.0      -10.0    1419.0      -11.0      AA   

   tailnum  flight origin dest  air_time  distance  hour  minute  
13  N3JLAA    1094    SEA  DFW     184.0      1660   5.0    57.0  
17  N3JFAA    2240    SEA  ORD     206.0      1721   6.0     0.0  
58  N3KNAA    1308    SEA  DFW     188.0      1660   7.0     4.0  
62  N3DNAA     236    SEA  JFK     281.0      2422   7.0     8.0  
86  N3DSAA    1236    SEA  ORD     202.0      1721   8.0    10.0

In [6]:
df_flights.loc[ np.all([df_flights['carrier'] == "AA", df_flights['origin'] == "SEA"], axis=0) ].head()

year  month  day  dep_time  dep_delay  arr_time  arr_delay carrier  \
13  2014      1    1     557.0       -3.0    1134.0      -16.0      AA   
17  2014      1    1     600.0        0.0    1151.0      -19.0      AA   
58  2014      1    1     704.0       -6.0    1245.0      -20.0      AA   
62  2014      1    1     708.0       -7.0    1510.0      -19.0      AA   
86  2014      1    1     810.0      -10.0    1419.0      -11.0      AA   

   tailnum  flight origin dest  air_time  distance  hour  minute  
13  N3JLAA    1094    SEA  DFW     184.0      1660   5.0    57.0  
17  N3JFAA    2240    SEA  ORD     206.0      1721   6.0     0.0  
58  N3KNAA    1308    SEA  DFW     188.0      1660   7.0     4.0  
62  N3DNAA     236    SEA  JFK     281.0      2422   7.0     8.0  
86  N3DSAA    1236    SEA  ORD     202.0      1721   8.0    10.0

#### wrong way

In [36]:
(df_flights['carrier'] == "AA") and (df_flights['origin'] == "SEA")

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

#### explains the use of numpy.all, numpy.any

In [46]:
np.all([df_flights['carrier'] == "AA", df_flights['origin'] == "SEA"], axis=1)

array([False, False])

In [47]:
np.all([df_flights['carrier'] == "AA", df_flights['origin'] == "SEA"])

False